// Airline marks are owned by their respective airlines. Source: airlogos 1.0.7 (MIT).
(function(root){const logos={
  "American Airlines": "AA.svg",
  "LATAM": "LA.png",
  "GOL": "G3.png",
  "Azul": "AD.png",
  "Delta Air Lines": "DL.svg",
  "United Airlines": "UA.svg",
  "Air Canada": "AC.svg",
  "Air France": "AF.svg",
  "KLM": "KL.svg",
  "Lufthansa": "LH.svg",
  "British Airways": "BA.svg",
  "Iberia": "IB.svg",
  "TAP Air Portugal": "TP.svg",
  "Copa Airlines": "CM.png",
  "Avianca": "AV.svg",
  "Aeromexico": "AM.png",
  "Aerolineas Argentinas": "AR.png",
  "Emirates": "EK.svg",
  "Qatar Airways": "QR.svg",
  "Etihad Airways": "EY.svg",
  "Turkish Airlines": "TK.svg",
  "ITA Airways": "AZ.svg",
  "Swiss": "LX.svg",
  "Austrian Airlines": "OS.svg",
  "Finnair": "AY.svg",
  "SAS Scandinavian": "SK.svg",
  "Ryanair": "FR.png",
  "easyJet": "U2.png",
  "Vueling": "VY.svg",
  "Transavia": "HV.png",
  "Air Europa": "UX.svg",
  "Singapore Airlines": "SQ.svg",
  "Cathay Pacific": "CX.svg",
  "Japan Airlines": "JL.svg",
  "ANA All Nippon Airways": "NH.svg",
  "Korean Air": "KE.svg",
  "Air China": "CA.svg",
  "China Southern": "CZ.svg",
  "Thai Airways": "TG.svg",
  "Qantas": "QF.svg",
  "Air New Zealand": "NZ.png",
  "Ethiopian Airlines": "ET.svg",
  "South African Airways": "SA.svg",
  "EgyptAir": "MS.svg",
  "Alaska Airlines": "AS.svg",
  "JetBlue": "B6.svg",
  "Southwest Airlines": "WN.svg",
  "Sky Airline": "H2.png",
  "JetSMART": "JA.png",
  "Wingo": "P5.png",
  "Air Arabia": "G9.svg",
  "flydubai": "FZ.svg"
};if(typeof module === "object" && module.exports)module.exports=logos;else root.AIRLINE_LOGOS=logos;})(typeof globalThis !== "undefined" ? globalThis : this);
